In [6]:
import tensorflow as tf
t = tf.constant([1,2,3,4])
sess = tf.InteractiveSession()

In [7]:
tf.shape(t).eval()

array([4])

In [11]:
matrix1 = tf.constant([[3,3]])
matrix2 = tf.constant([[2],[2]])
(matrix1+matrix2).eval()

array([[5, 5],
       [5, 5]])

In [13]:
tf.matmul(matrix1,matrix2).eval()

array([[12]])

In [14]:
(matrix1*matrix2).eval()

array([[6, 6],
       [6, 6]])

In [16]:
a= tf.random_normal([3]).eval()

In [19]:
print(a)

[-1.0156337   1.27986944 -0.60117537]


In [20]:
b = tf.random_uniform([2]).eval()

In [21]:
print(b)

[ 0.50894785  0.85226035]


In [23]:
tf.random_uniform([2,3]).eval()

array([[ 0.57643485,  0.54048526,  0.5450505 ],
       [ 0.07537615,  0.49446368,  0.10196781]], dtype=float32)

In [26]:
x = [[1.,2.],[3.,4.]]

In [27]:
tf.reduce_mean(x).eval()

2.5

In [28]:
tf.reduce_mean(x,axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [29]:
tf.reduce_sum(x).eval()

10.0

In [30]:
tf.reduce_sum(x,axis = 0).eval()

array([ 4.,  6.], dtype=float32)

In [32]:
tf.reduce_sum(x,axis= 1).eval()

array([ 3.,  7.], dtype=float32)

In [33]:
tf.reduce_mean(tf.reduce_sum(x,axis = -1)).eval()

5.0

In [36]:
x= [[0,2,2],[2,2,0]]
tf.argmax(x,axis =0).eval()

array([1, 0, 0], dtype=int64)

In [38]:
import numpy as np
t= np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])

In [39]:
t.shape

(2, 2, 3)

In [40]:
tf.reshape(t,shape=[-1,3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
tf.reshape(t,shape=[-1,1,3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [43]:
tf.squeeze([[0],[1],[2]]).eval()

array([0, 1, 2])

In [44]:
## one hot

In [47]:
t = tf.one_hot([[0],[1],[2],[0]],depth = 3).eval()
tf.reshape(t,shape= [-1,3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

In [48]:
tf.cast([1.8,2.2,3.3,4.9],tf.int32).eval()

array([1, 2, 3, 4])

In [49]:
x = [1,4]
y = [2,5]
z = [3,6]

tf.stack([x,y,z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
tf.stack([x,y,z],axis =1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
for x,y in zip([1,2,3],[4,5,6]):
    print(x,y)

1 4
2 5
3 6
