In [3]:
import tensorflow as tf
import matplotlib.pyplot as plt

In [1]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]


In [4]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)


In [5]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')


In [6]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b


In [7]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [9]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)

In [10]:
train = optimizer.minimize(cost)

In [11]:
sess = tf.Session()

In [12]:
sess.run(tf.global_variables_initializer())

In [15]:
for step in range (2001):
    cost_val,hy_val,_ = sess.run([cost,hypothesis,train],feed_dict ={x1: x1_data,x2: x2_data,x3: x3_data,Y:y_data})
    if step % 10 ==0:
        print(step,'cost:',cost_val,'\nPrediction:\n',hy_val)

0 cost: 10.0977 
Prediction:
 [ 156.56288147  181.32897949  182.52874756  195.78074646  138.87759399]
10 cost: 10.0471 
Prediction:
 [ 156.55084229  181.33717346  182.52500916  195.77841187  138.88804626]
20 cost: 9.99681 
Prediction:
 [ 156.53884888  181.34535217  182.52128601  195.77607727  138.89848328]
30 cost: 9.94675 
Prediction:
 [ 156.52690125  181.35353088  182.51756287  195.77377319  138.90890503]
40 cost: 9.89701 
Prediction:
 [ 156.51495361  181.36164856  182.51385498  195.7714386   138.91926575]
50 cost: 9.8475 
Prediction:
 [ 156.50306702  181.36978149  182.51016235  195.76914978  138.92962646]
60 cost: 9.7983 
Prediction:
 [ 156.49119568  181.37786865  182.50646973  195.76683044  138.93992615]
70 cost: 9.74931 
Prediction:
 [ 156.47935486  181.38595581  182.50280762  195.76457214  138.95022583]
80 cost: 9.70065 
Prediction:
 [ 156.46755981  181.39399719  182.49914551  195.76226807  138.96047974]
90 cost: 9.65221 
Prediction:
 [ 156.45579529  181.40203857  182.4954834   1

890 cost: 6.51267 
Prediction:
 [ 155.60906982  181.97956848  182.23228455  195.59860229  139.70419312]
900 cost: 6.48138 
Prediction:
 [ 155.59959412  181.98602295  182.22932434  195.59680176  139.71235657]
910 cost: 6.45017 
Prediction:
 [ 155.59013367  181.99249268  182.22637939  195.59506226  139.72053528]
920 cost: 6.41922 
Prediction:
 [ 155.58070374  181.99893188  182.22346497  195.59329224  139.72865295]
930 cost: 6.38844 
Prediction:
 [ 155.57130432  182.00531006  182.22053528  195.59153748  139.73677063]
940 cost: 6.35777 
Prediction:
 [ 155.56192017  182.01171875  182.21760559  195.58976746  139.74485779]
950 cost: 6.32728 
Prediction:
 [ 155.55256653  182.01808167  182.2146759   195.58802795  139.75292969]
960 cost: 6.29698 
Prediction:
 [ 155.54324341  182.02444458  182.21179199  195.58627319  139.76098633]
970 cost: 6.26679 
Prediction:
 [ 155.53392029  182.03079224  182.20890808  195.58454895  139.76901245]
980 cost: 6.23681 
Prediction:
 [ 155.5246582   182.03712463  18

 [ 154.94042969  182.43515015  182.02380371  195.47555542  140.27865601]
1680 cost: 4.49106 
Prediction:
 [ 154.93273926  182.44041443  182.02139282  195.47416687  140.28526306]
1690 cost: 4.47059 
Prediction:
 [ 154.92504883  182.44561768  182.01898193  195.47277832  140.29180908]
1700 cost: 4.45021 
Prediction:
 [ 154.91738892  182.45083618  182.01660156  195.47140503  140.29837036]
1710 cost: 4.42993 
Prediction:
 [ 154.90975952  182.45605469  182.01422119  195.470047    140.30490112]
1720 cost: 4.40975 
Prediction:
 [ 154.90211487  182.46124268  182.01184082  195.46867371  140.31140137]
1730 cost: 4.38969 
Prediction:
 [ 154.89451599  182.46641541  182.00946045  195.46730042  140.31790161]
1740 cost: 4.36972 
Prediction:
 [ 154.88693237  182.47157288  182.00709534  195.46595764  140.32440186]
1750 cost: 4.34988 
Prediction:
 [ 154.87937927  182.47673035  182.00473022  195.46458435  140.33084106]
1760 cost: 4.33011 
Prediction:
 [ 154.87182617  182.48187256  182.00238037  195.463241

In [16]:
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [17]:
X = tf.placeholder(tf.float32,shape=[None,3])

In [18]:
Y= tf.placeholder(tf.float32,shape=[None,1])

In [20]:
W = tf.Variable(tf.random_normal([3,1]),name = 'weight')

In [21]:
b = tf.Variable(tf.random_normal([1]),name = 'bias')

In [22]:
hypothesis = tf.matmul(X,W) +b

In [23]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [24]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)

In [25]:
train = optimizer.minimize(cost)

In [26]:
sess = tf.Session()

In [27]:
sess.run(tf.global_variables_initializer())

In [29]:
for step in range(2001):
    cost_val,hy_val,_ = sess.run([cost,hypothesis,train],feed_dict = {X:x_data,Y:y_data})
    if step %10 ==0:
        print(step,'cost:',cost_val, '\nPrediction\n',hy_val)

0 cost: 0.317208 
Prediction
 [[ 151.31970215]
 [ 184.70175171]
 [ 180.61233521]
 [ 196.61778259]
 [ 141.47305298]]
10 cost: 0.317101 
Prediction
 [[ 151.31941223]
 [ 184.70195007]
 [ 180.61225891]
 [ 196.61755371]
 [ 141.47346497]]
20 cost: 0.317002 
Prediction
 [[ 151.31912231]
 [ 184.70217896]
 [ 180.61219788]
 [ 196.61735535]
 [ 141.47387695]]
30 cost: 0.316897 
Prediction
 [[ 151.31884766]
 [ 184.70239258]
 [ 180.61213684]
 [ 196.61714172]
 [ 141.47428894]]
40 cost: 0.316795 
Prediction
 [[ 151.31855774]
 [ 184.70259094]
 [ 180.61206055]
 [ 196.6169281 ]
 [ 141.47470093]]
50 cost: 0.316687 
Prediction
 [[ 151.31828308]
 [ 184.70280457]
 [ 180.61199951]
 [ 196.61671448]
 [ 141.47512817]]
60 cost: 0.316583 
Prediction
 [[ 151.31799316]
 [ 184.70301819]
 [ 180.61192322]
 [ 196.61650085]
 [ 141.47554016]]
70 cost: 0.316476 
Prediction
 [[ 151.31771851]
 [ 184.70321655]
 [ 180.61186218]
 [ 196.61627197]
 [ 141.47595215]]
80 cost: 0.316372 
Prediction
 [[ 151.31745911]
 [ 184.70343018]


800 cost: 0.309631 
Prediction
 [[ 151.29971313]
 [ 184.71678162]
 [ 180.60786438]
 [ 196.60153198]
 [ 141.5038147 ]]
810 cost: 0.30955 
Prediction
 [[ 151.29946899]
 [ 184.71691895]
 [ 180.60778809]
 [ 196.60131836]
 [ 141.50413513]]
820 cost: 0.309457 
Prediction
 [[ 151.29927063]
 [ 184.71710205]
 [ 180.60775757]
 [ 196.60112   ]
 [ 141.50450134]]
830 cost: 0.309385 
Prediction
 [[ 151.29904175]
 [ 184.7172699 ]
 [ 180.60772705]
 [ 196.60095215]
 [ 141.50485229]]
840 cost: 0.30929 
Prediction
 [[ 151.29884338]
 [ 184.71743774]
 [ 180.60766602]
 [ 196.60075378]
 [ 141.50520325]]
850 cost: 0.309203 
Prediction
 [[ 151.29862976]
 [ 184.71760559]
 [ 180.60762024]
 [ 196.60055542]
 [ 141.5055542 ]]
860 cost: 0.309117 
Prediction
 [[ 151.29841614]
 [ 184.71775818]
 [ 180.60757446]
 [ 196.60035706]
 [ 141.50590515]]
870 cost: 0.309039 
Prediction
 [[ 151.29818726]
 [ 184.71791077]
 [ 180.60752869]
 [ 196.60015869]
 [ 141.50624084]]
880 cost: 0.308952 
Prediction
 [[ 151.29798889]
 [ 184.71

1800 cost: 0.301868 
Prediction
 [[ 151.28152466]
 [ 184.73083496]
 [ 180.60430908]
 [ 196.58305359]
 [ 141.53573608]]
1810 cost: 0.301793 
Prediction
 [[ 151.28138733]
 [ 184.73097229]
 [ 180.60429382]
 [ 196.58288574]
 [ 141.53604126]]
1820 cost: 0.301727 
Prediction
 [[ 151.28123474]
 [ 184.7310791 ]
 [ 180.60426331]
 [ 196.58270264]
 [ 141.53630066]]
1830 cost: 0.301652 
Prediction
 [[ 151.28108215]
 [ 184.73118591]
 [ 180.60421753]
 [ 196.58251953]
 [ 141.53659058]]
1840 cost: 0.301579 
Prediction
 [[ 151.28094482]
 [ 184.73130798]
 [ 180.60420227]
 [ 196.58235168]
 [ 141.53689575]]
1850 cost: 0.301511 
Prediction
 [[ 151.28079224]
 [ 184.73141479]
 [ 180.60417175]
 [ 196.58216858]
 [ 141.53717041]]
1860 cost: 0.301441 
Prediction
 [[ 151.28065491]
 [ 184.73153687]
 [ 180.60415649]
 [ 196.58200073]
 [ 141.53746033]]
1870 cost: 0.301363 
Prediction
 [[ 151.28050232]
 [ 184.73165894]
 [ 180.60411072]
 [ 196.58180237]
 [ 141.53773499]]
1880 cost: 0.301303 
Prediction
 [[ 151.28034973

In [30]:
import numpy as np

In [32]:
    xy = np.loadtxt('data-01-test-score.csv',delimiter=',',dtype=np.float32)

In [34]:
x_data = xy[:,0:-1]
print(x_data.shape,x_data,len(x_data))

(6, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]] 6


In [36]:
y_data = xy[:,[-1]]
print(y_data.shape,y_data)

(6, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]]


In [37]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [38]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [39]:
hypothesis = tf.matmul(X, W) + b

In [40]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [41]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [42]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the loop.
for step in range(2001):
   cost_val, hy_val, _ = sess.run(
       [cost, hypothesis, train], 
       feed_dict={X: x_data, Y: y_data})
   if step % 10 == 0:
       print(step, "Cost: ", cost_val, 
                  "\nPrediction:\n", hy_val)


# Ask my score
print("Your score will be ", sess.run(hypothesis, 
           feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis, 
           feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


0 Cost:  42.773 
Prediction:
 [[ 147.99705505]
 [ 175.74655151]
 [ 174.31112671]
 [ 190.20687866]
 [ 133.03126526]
 [  98.06291962]]
10 Cost:  4.48249 
Prediction:
 [[ 153.75883484]
 [ 182.68455505]
 [ 181.14064026]
 [ 197.64451599]
 [ 138.32598877]
 [ 101.96764374]]
20 Cost:  4.46784 
Prediction:
 [[ 153.79168701]
 [ 182.73478699]
 [ 181.18460083]
 [ 197.69250488]
 [ 138.36689758]
 [ 101.9992218 ]]
30 Cost:  4.45506 
Prediction:
 [[ 153.7857666 ]
 [ 182.73835754]
 [ 181.18258667]
 [ 197.69042969]
 [ 138.37216187]
 [ 102.00454712]]
40 Cost:  4.44233 
Prediction:
 [[ 153.77961731]
 [ 182.74160767]
 [ 181.18031311]
 [ 197.68803406]
 [ 138.37721252]
 [ 102.00966644]]
50 Cost:  4.4297 
Prediction:
 [[ 153.77346802]
 [ 182.74482727]
 [ 181.17799377]
 [ 197.68565369]
 [ 138.38221741]
 [ 102.01477814]]
60 Cost:  4.4171 
Prediction:
 [[ 153.7673645 ]
 [ 182.74807739]
 [ 181.17572021]
 [ 197.68325806]
 [ 138.38723755]
 [ 102.01985931]]
70 Cost:  4.40462 
Prediction:
 [[ 153.76124573]
 [ 182.751

750 Cost:  3.70205 
Prediction:
 [[ 153.39105225]
 [ 182.94772339]
 [ 181.03645325]
 [ 197.53186035]
 [ 138.7013855 ]
 [ 102.32805634]]
760 Cost:  3.69361 
Prediction:
 [[ 153.38623047]
 [ 182.95030212]
 [ 181.03469849]
 [ 197.52986145]
 [ 138.70552063]
 [ 102.33194733]]
770 Cost:  3.68518 
Prediction:
 [[ 153.38140869]
 [ 182.95288086]
 [ 181.03291321]
 [ 197.52783203]
 [ 138.7096405 ]
 [ 102.33582306]]
780 Cost:  3.6768 
Prediction:
 [[ 153.37660217]
 [ 182.95545959]
 [ 181.03115845]
 [ 197.52581787]
 [ 138.71374512]
 [ 102.33969116]]
790 Cost:  3.66847 
Prediction:
 [[ 153.37181091]
 [ 182.95802307]
 [ 181.02940369]
 [ 197.52381897]
 [ 138.71784973]
 [ 102.34353638]]
800 Cost:  3.6602 
Prediction:
 [[ 153.36705017]
 [ 182.96058655]
 [ 181.02766418]
 [ 197.52183533]
 [ 138.72193909]
 [ 102.34736633]]
810 Cost:  3.65198 
Prediction:
 [[ 153.36230469]
 [ 182.96311951]
 [ 181.02592468]
 [ 197.51983643]
 [ 138.72601318]
 [ 102.35118103]]
820 Cost:  3.64378 
Prediction:
 [[ 153.3575592 ]


1510 Cost:  3.17171 
Prediction:
 [[ 153.06642151]
 [ 183.12319946]
 [ 180.91893005]
 [ 197.39094543]
 [ 138.9864502 ]
 [ 102.58428192]]
1520 Cost:  3.166 
Prediction:
 [[ 153.06268311]
 [ 183.1252594 ]
 [ 180.91758728]
 [ 197.38925171]
 [ 138.98985291]
 [ 102.5871582 ]]
1530 Cost:  3.16035 
Prediction:
 [[ 153.0589447 ]
 [ 183.12728882]
 [ 180.91625977]
 [ 197.38755798]
 [ 138.9932251 ]
 [ 102.59001923]]
1540 Cost:  3.15473 
Prediction:
 [[ 153.05523682]
 [ 183.12931824]
 [ 180.91493225]
 [ 197.38586426]
 [ 138.99659729]
 [ 102.59288025]]
1550 Cost:  3.14913 
Prediction:
 [[ 153.05152893]
 [ 183.13134766]
 [ 180.91362   ]
 [ 197.38417053]
 [ 138.99995422]
 [ 102.59571075]]
1560 Cost:  3.14356 
Prediction:
 [[ 153.0478363 ]
 [ 183.13337708]
 [ 180.91230774]
 [ 197.38249207]
 [ 139.00331116]
 [ 102.59854889]]
1570 Cost:  3.13802 
Prediction:
 [[ 153.04415894]
 [ 183.13537598]
 [ 180.91098022]
 [ 197.38079834]
 [ 139.00665283]
 [ 102.60137939]]
1580 Cost:  3.1325 
Prediction:
 [[ 153.040